# .readthedocs.yaml

version: 2

build:
  os: ubuntu-latest
  tools:
    python: "3.10.12"

sphinx:
  configuration: docs/conf.py

python:
  version: 3.10.12  
  install:
    - requirements: docs/requirements.txt
